### ISSUE TITLE
Recipe Recommendation Engine 

### ISSUE THREAD

**Issue by spencer-jin** [cs130-w21/12#1]
## Epic
Recommend a list of recipes based on a user's list of recipes, dietary restrictions, and cooking preferences.

The user will enter in a list of ingredients and input their dietary preferences. Then, after clicking the recommendation button, the user will be directed to a new page with recipes using those ingredients and abiding by their preferences. There will be eight recipes listed with their names and their corresponding images. If the user wishes to see more recipes, there will be a button that generates more recipes for the user to view.

## User Stories 
- [x] #3 Recommendation engine - based on ingredients
- [x] #9 Recommendation engine - user preference
- [x] #10 List recipes with images
