### ISSUE TITLE
User Profile Management

### ISSUE THREAD

**Issue by spencer-jin** [cs130-w21/12#2]
## Epic
User profile management system to create and maintain profiles for each user. 

Users will be able to signup, login, and logout of their profile. They will also have an option to login with their social media accounts, like a Facebook or Google account. Users will also be able to choose a username and profile picture, and change them if they want to. If users wish to leave the app entirely, they also have the option to delete their profile.

## User Stories
- [x] #4 Sign-up
- [x] #11 Login, logout
- [x] #15 Delete profile
- [x] #34 Change user profile info
- [x] #26 Profile page UI
- [x] #30 Social media login
- [x] #32 Implement profile picture/avatar
